# Generated by Django 5.2.4 on 2025-07-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('D', 'Done')], max_length=10),
        ),
    ]
