# Generated by Django 5.2.4 on 2025-07-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('D', 'Done')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
