# Generated by Django 5.2.4 on 2025-08-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tasks_author_alter_tasks_description_and_more'),
    ]

    operations = [
    ]
